---
title: "Monica's Blog"
date: 2019-01-10

title: Monica's Blog 
author: Monica May 
email: msm065@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. I will be posting very cool stuff on this page.

# social links
twitter_username: your-twitter-handle
github_username:  @monicasmay

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
